### ISSUE TITLE
Still able to duplicate stash items

### ISSUE THREAD

**Issue by LifeStyleRolePlay** [ihyajb/aj-inventory#10]
Storing items doesn't save in the stash, you can also pull items out of the stash, close it and then reopen it and the item will still be in the stash and you can continue to pull it out

**Comment by ihyajb** [comment]
you have an outdated qb-core

**Comment by LifeStyleRolePlay** [comment]
I have the newest qb-core. I updated to the most recent one whenever new updates come out

**Comment by LifeStyleRolePlay** [comment]
I have the newest qb-core from today and the problem with duplication still persists for me

**Comment by GhzGarage** [comment]
Gotta use the new sql
