### ISSUE TITLE
Suggestion: update your fxmanifest.lua - provide ‘qb-inventory’

### ISSUE THREAD

**Issue by sinfuljosh** [ihyajb/aj-inventory#11]
Instead for having to track down any other resources that specify qb-inventory as a dependency. Use _provide_ in your fxmanifest.lua to fulfill the dependency requirement.

`provide ‘qb-inventory’`

Add that to your fxmanifest.lua and you do not need to modify the other resources.

Here is the documentation and the source.

**provide**

Marks the current resource as a replacement for the specified resource. This means it'll start instead of the specified resource, if another resource requires it, and will act as if it is said resource if started.

[FiveM Scripting Resource](https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/)

**Comment by ihyajb** [comment]
Wow I didn't know that was such a thing. I appreciate you also adding the documentation for it! I'm currently away but when I get back i will for-sure be adding this!

**Comment by ihyajb** [comment]
added to main build
