### ISSUE TITLE
Script error while trying to open the glovebox or trunk

### ISSUE THREAD

**Issue by ItsBentix** [ihyajb/aj-inventory#15]
I am always getting this error when trying to open the glovebox or trunk:
[aj-inventory] An error happens for query "SELECT items FROM gloveboxitems WHERE plate=? : ["PLZI1966"]": ER_BAD_FIELD_ERROR: Unknown column 'items' in 'field list'

**Comment by ihyajb** [comment]
are all your scripts up to date with the offical QBCore Build? Try running the SQL again

**Comment by ItsBentix** [comment]
i have only updated the qb core today and the inventory

**Comment by ItsBentix** [comment]
There are no columns created in the DB

**Comment by ItsBentix** [comment]
nvm I fixed it. There was an error in the DB
