### ISSUE TITLE
Shop error 

### ISSUE THREAD

**Issue by SoCallMeAstro** [ihyajb/aj-inventory#16]
So I've been trying to get this burger shot script to work for a bit now with your inventory because I love it so much, awesome work btw 👍 ( https://github.com/DrBlackBeard095/Qb-Burgershot )

Everything works flawlessly, but for some reason it breaks the shops, I'm not sure, and it throws this error.
Seems to break the inventory a little bit, and deletes it.

Do you happen to know if there's anything that could fix this issue? Or would that not be possible

Thanks,
Tom

@aj-inventory/server/main.lua:931: attempt to index a nil value (local 'itemInfo')

**Comment by ihyajb** [comment]
is qb-shops up to date with the latest Official Build?

**Comment by SoCallMeAstro** [comment]
Uhm i'm pretty sure, let me just make sure real quick!

**Comment by SoCallMeAstro** [comment]
Omg I love you, of course it was something so stupidly simple. Thank you so much lmao!

**Comment by ihyajb** [comment]
anytime
