### ISSUE TITLE
Controls don't work after closing inventory

### ISSUE THREAD

**Issue by scarecrow313** [ihyajb/aj-inventory#17]
Hey!

Just installed latest version of aj-inventory and qbcore. Inventory works and looks great. But when closing it, None of the controls work and I can't do anything. 

The only keys that work are the F1 etc keys (cant type anything though)

**Comment by ihyajb** [comment]
did you rename the folder to something other then "aj-inventory"?

**Comment by scarecrow313** [comment]
apparently I need to go back to sleep. Yes that was the issue. I had forgot to remove main from the folder name. Thank you for the fast response. stay blessed.
