### ISSUE TITLE
Inventory Improvments

### ISSUE THREAD

**Issue by ProXiSee** [ihyajb/aj-inventory#18]
Yo, it will be nice if you add a delay to using items and opening inventory( actually you just hold tab and spam with it), and also fix ammo issue (sometimes ammo removing from the gun) and items moving issue.

inventory spam - https://streamable.com/8jy7qm
item spam - https://streamable.com/hpcoci
item moving issue - https://streamable.com/jne6jl

**Comment by xenfovn** [comment]
true , this is big bug
