### ISSUE TITLE
qb-inventory > aj-inventory

### ISSUE THREAD

**Issue by Cocaina-Ricky** [ihyajb/aj-inventory#19]
Hi,

So I added this to my server including qb-core and I can't seem to open the inventory.

**Comment by ihyajb** [comment]
are you using the latest Offical QBCore build? https://github.com/qbcore-framework

**Comment by Cocaina-Ricky** [comment]
> 
> 
> are you using the latest Offical QBCore build? https://github.com/qbcore-framework

I am yes. I am also using this: https://github.com/qbcore-framework/qb-core

There's no errors at all though.

**Comment by ihyajb** [comment]
did you rename it to something other then `aj-inventory`?

**Comment by Cocaina-Ricky** [comment]
No sir.

**Comment by ihyajb** [comment]
hmm weird I havent seen this issue yet, ill look into it right now

**Comment by ihyajb** [comment]
try /inventory see if that opens it
