### ISSUE TITLE
Inventory Close Issue

### ISSUE THREAD

**Issue by imtorchedbud** [ihyajb/aj-inventory#22]
hello,
i need help with the inventory to close it seems like i cant use items and it will close to just a mouse cursor no nui , not sure if need an nui call back and as for the using items i have no clue no errors. if you can help me with a code line that would be beautiful btw great job on this script

**Comment by imtorchedbud** [comment]
my discord is ImTorchedBud TTV#1291

**Comment by ihyajb** [comment]
what's the name of the folder for the inventory?

**Comment by imtorchedbud** [comment]
I had figured it out actually it was set to false on is inv open so I set
it to true and it works great!
