### ISSUE TITLE
Giving weapons/IDs/Drivers Licenses is incorrect

### ISSUE THREAD

**Issue by DannysRP** [ihyajb/aj-inventory#23]
Lets say I have 2 pistols with 2 different serial numbers and ammo. I have 1 pistol with 30 ammo for example, and 1 with 0 ammo. If I try to hand someone my pistol with ammo it will instead hand that person my pistol with 0 ammo. Then when that person checks their inventory they will have a pistol with 30 ammo and the same serial number as the gun I tried to give them initially. If they hand me the pistol back I will have 2 pistols with the same ammo/same serial number. It also does this with ID Cards and DL. If I have my ID and someone elses ID and I try to give it back to them it will instead give them one of my ID cards and not the one I initially tried to hand them

**Comment by Wisfakim** [comment]
![image](https://user-images.githubusercontent.com/16806184/132724206-eeaaccaf-a94a-4453-a9a8-3fd54c0437d6.png)
Need To add slot when you give item to RemoveItem method. server side

**Comment by LifeStyleRolePlay** [comment]
Did you remove "false" and put item.slot?

**Comment by LifeStyleRolePlay** [comment]
I tried this and it worked but it would place the item in a random slot and not first slot that is open

**Comment by Kingsage311** [comment]
Are you using the default qb id card or a modified one? because its getting "item.info" so as long as you get no errors it should hand over the one you drag i peronally don't have this issue with the latest update & the defult qb id card
