### ISSUE TITLE
Remove IDs ?

### ISSUE THREAD

**Issue by OfficialRDB** [ihyajb/aj-inventory#34]
Since I don't like the random IDs behind names, is my question.
Can I just remove that without any issues or is that there with a reason ?

EXAMPLE:
secondInv.name = "glovebox-"..id
secondInv.label = "Glovebox-"..id

secondInv.name = "itemshop-"..id
secondInv.name = "traphouse-"..id
secondInv.name = "otherplayer-"..id

secondInv.name = "otherplayer-"..id
secondInv.label = "Player-"..id

secondInv.name = id
secondInv.label = "Dropped-"..tostring(id)

**Comment by ihyajb** [comment]
I mean ive never tried it but id assume it would be fine.
