### ISSUE TITLE
When giving an item from stash/ground will dupe the item

### ISSUE THREAD

**Issue by bruinp8n** [ihyajb/aj-inventory#37]
Dragging item from ground to give, causes duping

**Comment by ihyajb** [comment]
Are you running the latest `qb-core` and `aj-inventory`? Do you have a video of this happening

**Comment by scrubh** [comment]
This is happening to mee also, tested what he said and boom.

**Comment by SlomGom** [comment]
Check that you have the Primary key and key in the right place in the table in the database. I had similar problems and solved it by changing to this

https://github.com/qbcore-framework/qb-inventory/commit/c5d46d3eecddc681563d31b9d91bb09faa71c8bf#diff-76cdc62a33fa3e9e090428ce8a2ccfbbd4dc0c236a347f623de886c8efeb11a6

**Comment by ihyajb** [comment]
Yeah I myself and a bunch of people tested this and I can't reproduce it.
