### ISSUE TITLE
Can't give items

### ISSUE THREAD

**Issue by mrvampus** [ihyajb/aj-inventory#4]
When I try to give someone something it just exits out of the inventory without actually giving them anything

**Comment by ihyajb** [comment]
added a wip version of it after learning how to do it. Feel free to test and give feedback

**Comment by mrvampus** [comment]
Works just fine, but you should add the possibility to choose, who you give it to

**Comment by ihyajb** [comment]
Noted, will find how to add if if its simple enough will add it
