### ISSUE TITLE
Script error.

### ISSUE THREAD

**Issue by Grimsic93** [ihyajb/aj-inventory#6]
Getting this script error as alot of people ive seen have been getting it.
@aj-inventory/client/main.lua:125: attempt to index a nil value (global 'QBCore')

**Comment by ihyajb** [comment]
is your core updated to a recent build?

**Comment by Grimsic93** [comment]
Would have to check i know people are using it flawlessly on the verison im on.

**Comment by Grimsic93** [comment]
Is there a prior verison i could get or something to work with the other core.

**Comment by ihyajb** [comment]
give me like 10 mins i'll add support back for the older cores

**Comment by Grimsic93** [comment]
Thank you!

**Comment by Grimsic93** [comment]
Is there a verison i could get before the latest. that will work with it

**Comment by ihyajb** [comment]
just updated just follow the README.md

**Comment by Grimsic93** [comment]
Awesome worked perfectly thank you!
