### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by dulkith** [ihyajb/aj-inventory#8]
How to fix this error? (I used new QBcore)
`[ script:aj-inventory] SCRIPT ERROR: @aj-inventory/server/main.lua:314: attempt to index a nil value (field '?')`

**Comment by ihyajb** [comment]
what were you doing when you got the error?

**Comment by dulkith** [comment]
> what were you doing when you got the error?

I used new QBcore, when I use inventory.

**Comment by ihyajb** [comment]
ah yeah, the main QBCore Inventory had an update. I think thats why everything is throwing errors. I will try and update it tmro

**Comment by dulkith** [comment]
> ah yeah, the main QBCore Inventory had an update. I think thats why everything is throwing errors. I will try and update it tmro

Thank you bro. I'm going to use your script.

**Comment by ihyajb** [comment]
fixed
