### ISSUE TITLE
dupplicate

### ISSUE THREAD

**Issue by p4zinee** [ihyajb/aj-inventory#9]
when i spam e (on stash) and tab to get #error stash it will dupplicate item from stash to #error stash

**Comment by ihyajb** [comment]
okay will look into it, any chance you can get a vid so i can try and reproduce it?

**Comment by p4zinee** [comment]
![image](https://user-images.githubusercontent.com/64763166/127607988-e13b35fb-0a41-407c-8568-6b1298caeae8.png)

**Comment by p4zinee** [comment]
just put a wait() to 
![image](https://user-images.githubusercontent.com/64763166/127611397-48309020-186a-47f4-90f8-5a4f2decc33e.png)
and 
![image](https://user-images.githubusercontent.com/64763166/127611446-a51d0922-62c5-47cb-a094-59ce992baebe.png)
can solved it
but look stupid, please fix it :(

**Comment by p4zinee** [comment]
just put a wait() to 
![image](https://user-images.githubusercontent.com/64763166/127611397-48309020-186a-47f4-90f8-5a4f2decc33e.png)
and 
![image](https://user-images.githubusercontent.com/64763166/127611446-a51d0922-62c5-47cb-a094-59ce992baebe.png)
can solved it
but look stupid, please fix it :(

**Comment by ihyajb** [comment]
yeah, i didnt have that because it looked weird at times, im pretty sure the issues lies within QBCore itself so Ill talk to them and see if we can figure it out, because it seems to be happening on qb-inventory also

**Comment by p4zinee** [comment]
> yeah, i didnt have that because it looked weird at times, im pretty sure the issues lies within QBCore itself so Ill talk to them and see if we can figure it out, because it seems to be happening on qb-inventory also

i just get reported from my member, i will recording it ,w8 me

**Comment by ihyajb** [comment]
just pushed an update, see if that fixes it

**Comment by p4zinee** [comment]
https://www.youtube.com/watch?v=etIhMOPbgWs , i not test the last change but here is how it get bug
https://www.youtube.com/watch?v=etIhMOPbgWs

**Comment by ihyajb** [comment]
yeah that doesn't happen to me, just tested and i can't dupe through item, would seem you save something outdated breaking stuff
